# Changes here will be overwritten by Copier
_commit: '5273708'
_src_path: https://github.com/oarepo/nrp-app-copier
languages: cs
repository_description: Here you can play with all of the features it has to offer!
repository_human_name: CESNET Invenio Sandbox
